-- ============================================================================
-- FinOps WebApp - Schema Azure SQL Database
-- Espelha as 5 fontes de dados hoje lidas de data/*.csv
-- Execute uma vez, logo após o provisionamento do banco.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- dbo.FinOpsRecommendations  (azure_finops_multiservice_recommendation.csv)
-- ----------------------------------------------------------------------------
CREATE TABLE dbo.FinOpsRecommendations (
    TenantId NVARCHAR(200) NULL,
    TenantName NVARCHAR(MAX) NULL,
    SubscriptionId NVARCHAR(200) NULL,
    SubscriptionName NVARCHAR(MAX) NULL,
    ResourceId NVARCHAR(400) NULL,
    ResourceName NVARCHAR(MAX) NULL,
    ResourceType NVARCHAR(MAX) NULL,
    ResourceGroup NVARCHAR(MAX) NULL,
    Location NVARCHAR(MAX) NULL,
    ServiceType NVARCHAR(MAX) NULL,
    PricingCategory NVARCHAR(MAX) NULL,
    AnalysisType NVARCHAR(MAX) NULL,
    AnalysisMethod NVARCHAR(MAX) NULL,
    MetricSource NVARCHAR(MAX) NULL,
    PropertySource NVARCHAR(MAX) NULL,
    RuleEvaluationMode NVARCHAR(MAX) NULL,
    RecommendationAction NVARCHAR(MAX) NULL,
    ActionLabel NVARCHAR(MAX) NULL,
    ActionSummary NVARCHAR(MAX) NULL,
    ActionCategory NVARCHAR(MAX) NULL,
    IsActionable BIT NULL,
    IsDestructive BIT NULL,
    RecommendationPractice NVARCHAR(MAX) NULL,
    CombinedPractice NVARCHAR(MAX) NULL,
    RecommendationReason NVARCHAR(MAX) NULL,
    Priority NVARCHAR(MAX) NULL,
    Confidence NVARCHAR(MAX) NULL,
    PrimaryRuleType NVARCHAR(MAX) NULL,
    PrimaryMetric NVARCHAR(MAX) NULL,
    PrimaryMetricValue FLOAT NULL,
    PrimaryProperty NVARCHAR(MAX) NULL,
    PrimaryPropertyValue NVARCHAR(MAX) NULL,
    PrimaryPropertyRule NVARCHAR(MAX) NULL,
    MetricPattern NVARCHAR(MAX) NULL,
    MetricDataPoints FLOAT NULL,
    MetricExpectedDataPoints FLOAT NULL,
    MetricCoverageRatio FLOAT NULL,
    MetricCoverageStatus NVARCHAR(MAX) NULL,
    WithheldReason NVARCHAR(MAX) NULL,
    HeldBackFrom NVARCHAR(MAX) NULL,
    SavingsStatus NVARCHAR(MAX) NULL,
    EstimatedMonthlyCostIncrease FLOAT NULL,
    EstimatedAnnualCostIncrease FLOAT NULL,
    RiskAdjustedMonthlySavings FLOAT NULL,
    RiskAdjustedAnnualSavings FLOAT NULL,
    SavingsMethod NVARCHAR(MAX) NULL,
    TargetSku NVARCHAR(MAX) NULL,
    TargetSkuStatus NVARCHAR(MAX) NULL,
    SecondaryAction NVARCHAR(MAX) NULL,
    SecondaryActionLabel NVARCHAR(MAX) NULL,
    SecondaryMonthlySavings FLOAT NULL,
    SecondaryAnnualSavings FLOAT NULL,
    CurrentSku NVARCHAR(MAX) NULL,
    CurrentVCpus FLOAT NULL,
    CurrentMemoryGB FLOAT NULL,
    TargetVCpus FLOAT NULL,
    TargetMemoryGB FLOAT NULL,
    TargetOptions NVARCHAR(MAX) NULL,
    MetricInterval NVARCHAR(MAX) NULL,
    PowerState NVARCHAR(MAX) NULL,
    CurrentMonthToDateCost FLOAT NULL,
    DailyRunRate FLOAT NULL,
    ClosedMonthDailyAverage FLOAT NULL,
    CostIncreaseMethod NVARCHAR(MAX) NULL,
    CostCurrency NVARCHAR(MAX) NULL,
    CostLookbackMonths FLOAT NULL,
    PeriodCost FLOAT NULL,
    MetricPointCount FLOAT NULL,
    PropertyCondition NVARCHAR(MAX) NULL,
    MetricCollectionStatus NVARCHAR(MAX) NULL,
    ConfiguredMetricCount FLOAT NULL,
    AvailableMetricCount FLOAT NULL,
    MissingMetricCount FLOAT NULL,
    MissingMetrics NVARCHAR(MAX) NULL,
    HasMetricAnalysis BIT NULL,
    HasPropertyAnalysis BIT NULL,
    MetricAverage FLOAT NULL,
    ObservedPeak FLOAT NULL,
    MetricStandardDeviation FLOAT NULL,
    MetricCoefficientOfVariation FLOAT NULL,
    TenantsExpected FLOAT NULL,
    TenantsSucceeded FLOAT NULL,
    TenantsFailed FLOAT NULL,
    TriggeredRulesCount FLOAT NULL,
    PropertyRulesCount FLOAT NULL,
    TriggeredRules NVARCHAR(MAX) NULL,
    TriggeredMetricRules NVARCHAR(MAX) NULL,
    TriggeredPropertyRules NVARCHAR(MAX) NULL,
    MetricAnalysis NVARCHAR(MAX) NULL,
    PropertyAnalysis NVARCHAR(MAX) NULL,
    MetricAnalysisAvailable BIT NULL,
    PropertyAnalysisAvailable BIT NULL,
    MonthlyCost FLOAT NULL,
    AnnualCost FLOAT NULL,
    EstimatedMonthlySavings FLOAT NULL,
    EstimatedAnnualSavings FLOAT NULL,
    SavingsMultiplier FLOAT NULL,
    ConfidenceWeight FLOAT NULL,
    CostSource NVARCHAR(MAX) NULL,
    SavingsCalculationMethod NVARCHAR(MAX) NULL,
    Tags NVARCHAR(MAX) NULL,
    TagOwner NVARCHAR(MAX) NULL,
    TagApplication NVARCHAR(MAX) NULL,
    TagEnvironment NVARCHAR(MAX) NULL,
    TagCostCenter NVARCHAR(MAX) NULL,
    MonthsAvailable FLOAT NULL,
    CostCoverageStatus NVARCHAR(MAX) NULL,
    SavingsReliability NVARCHAR(MAX) NULL,
    RunId NVARCHAR(200) NULL,
    RunStartedAt NVARCHAR(64) NULL,
    EngineVersion NVARCHAR(MAX) NULL,
    ProcessingStatus NVARCHAR(MAX) NULL,
    Error NVARCHAR(MAX) NULL,
    rundate NVARCHAR(64) NULL
);
CREATE INDEX IX_FinOpsRecommendations_RunId ON dbo.FinOpsRecommendations (RunId);
CREATE INDEX IX_FinOpsRecommendations_ResourceId ON dbo.FinOpsRecommendations (ResourceId);

-- ----------------------------------------------------------------------------
-- dbo.FinOpsLatestRun  (vw_finops_latest_complete_run.csv)
-- Mesma estrutura de FinOpsRecommendations: é o snapshot já filtrado pelo
-- engine para a última execução publicada. Materializado como tabela porque
-- a lógica de seleção ("última run completa/publicada") roda fora deste app.
-- ----------------------------------------------------------------------------
SELECT TOP 0 * INTO dbo.FinOpsLatestRun FROM dbo.FinOpsRecommendations;
CREATE INDEX IX_FinOpsLatestRun_ResourceId ON dbo.FinOpsLatestRun (ResourceId);

-- ----------------------------------------------------------------------------
-- dbo.FinOpsEngineRuns  (finops_engine_runs.csv)
-- ----------------------------------------------------------------------------
CREATE TABLE dbo.FinOpsEngineRuns (
    RunId NVARCHAR(200) NULL,
    RunStatus NVARCHAR(MAX) NULL,
    DataQualityStatus NVARCHAR(MAX) NULL,
    IsPublishable BIT NULL,
    RunScope NVARCHAR(MAX) NULL,
    TenantFilter NVARCHAR(MAX) NULL,
    SubscriptionFilter NVARCHAR(MAX) NULL,
    OutputCatalog NVARCHAR(MAX) NULL,
    OutputDatabase NVARCHAR(MAX) NULL,
    OutputTable NVARCHAR(MAX) NULL,
    PublishApproved BIT NULL,
    PublishedAt NVARCHAR(64) NULL,
    PublishedBy NVARCHAR(MAX) NULL,
    RunStartedAt NVARCHAR(64) NULL,
    RunFinishedAt NVARCHAR(64) NULL,
    EngineVersion NVARCHAR(MAX) NULL,
    RowsProduced FLOAT NULL,
    RowsPersisted FLOAT NULL,
    RowsFailed FLOAT NULL,
    TenantsExpected FLOAT NULL,
    TenantsSucceeded FLOAT NULL,
    TenantsFailed FLOAT NULL,
    IncrementalWriteFailures FLOAT NULL,
    MetricRows FLOAT NULL,
    MetricsUnavailableRows FLOAT NULL,
    MetricsPartialRows FLOAT NULL,
    MetricAvailabilityRate FLOAT NULL,
    MetricCompletenessRate FLOAT NULL,
    CostRows FLOAT NULL,
    CostFullCoverageRows FLOAT NULL,
    CostAvailabilityRate FLOAT NULL,
    CostFullCoverageRate FLOAT NULL,
    PricedSavingsRows FLOAT NULL,
    HeuristicSavingsRows FLOAT NULL,
    UnpricedSavingsRows FLOAT NULL,
    DegradedServices NVARCHAR(MAX) NULL,
    Notes NVARCHAR(MAX) NULL
);
CREATE INDEX IX_FinOpsEngineRuns_RunId ON dbo.FinOpsEngineRuns (RunId);

-- ----------------------------------------------------------------------------
-- dbo.FinOpsTargetOptions  (vw_finops_target_options.csv)
-- ----------------------------------------------------------------------------
CREATE TABLE dbo.FinOpsTargetOptions (
    rundate NVARCHAR(64) NULL,
    RunId NVARCHAR(200) NULL,
    TenantName NVARCHAR(MAX) NULL,
    SubscriptionName NVARCHAR(MAX) NULL,
    ResourceId NVARCHAR(400) NULL,
    ResourceName NVARCHAR(MAX) NULL,
    ResourceType NVARCHAR(MAX) NULL,
    ResourceGroup NVARCHAR(MAX) NULL,
    Location NVARCHAR(MAX) NULL,
    RecommendationAction NVARCHAR(MAX) NULL,
    ActionLabel NVARCHAR(MAX) NULL,
    ActionSummary NVARCHAR(MAX) NULL,
    SecondaryAction NVARCHAR(MAX) NULL,
    SecondaryActionLabel NVARCHAR(MAX) NULL,
    Priority NVARCHAR(MAX) NULL,
    Confidence NVARCHAR(MAX) NULL,
    SavingsReliability NVARCHAR(MAX) NULL,
    CostCoverageStatus NVARCHAR(MAX) NULL,
    MetricCollectionStatus NVARCHAR(MAX) NULL,
    MissingMetrics NVARCHAR(MAX) NULL,
    TagOwner NVARCHAR(MAX) NULL,
    TagApplication NVARCHAR(MAX) NULL,
    TagEnvironment NVARCHAR(MAX) NULL,
    TagCostCenter NVARCHAR(MAX) NULL,
    MonthlyCost FLOAT NULL,
    CurrentSku NVARCHAR(MAX) NULL,
    CurrentVCpus FLOAT NULL,
    CurrentMemoryGB FLOAT NULL,
    PowerState NVARCHAR(MAX) NULL,
    Profile NVARCHAR(MAX) NULL,
    IsPrimaryProfile BIT NULL,
    TargetUtilizationPct FLOAT NULL,
    TargetSku NVARCHAR(MAX) NULL,
    TargetVCpus FLOAT NULL,
    TargetMemoryGB FLOAT NULL,
    ProjectedPeakPct FLOAT NULL,
    MonthlySavings FLOAT NULL,
    OfficialConservativeSavings FLOAT NULL,
    PerformanceRisk NVARCHAR(MAX) NULL,
    Status NVARCHAR(MAX) NULL
);
CREATE INDEX IX_FinOpsTargetOptions_ResourceId ON dbo.FinOpsTargetOptions (ResourceId);
CREATE INDEX IX_FinOpsTargetOptions_RunId ON dbo.FinOpsTargetOptions (RunId);

-- ----------------------------------------------------------------------------
-- dbo.FinOpsTargetOptionsAllRuns  (vw_finops_target_options_all_runs.csv)
-- ----------------------------------------------------------------------------
CREATE TABLE dbo.FinOpsTargetOptionsAllRuns (
    rundate NVARCHAR(64) NULL,
    RunId NVARCHAR(200) NULL,
    RunStatus NVARCHAR(MAX) NULL,
    RunScope NVARCHAR(MAX) NULL,
    DataQualityStatus NVARCHAR(MAX) NULL,
    IsPublishable BIT NULL,
    TenantName NVARCHAR(MAX) NULL,
    SubscriptionName NVARCHAR(MAX) NULL,
    ResourceId NVARCHAR(400) NULL,
    ResourceName NVARCHAR(MAX) NULL,
    ResourceType NVARCHAR(MAX) NULL,
    ResourceGroup NVARCHAR(MAX) NULL,
    Location NVARCHAR(MAX) NULL,
    RecommendationAction NVARCHAR(MAX) NULL,
    ActionLabel NVARCHAR(MAX) NULL,
    SecondaryAction NVARCHAR(MAX) NULL,
    Priority NVARCHAR(MAX) NULL,
    Confidence NVARCHAR(MAX) NULL,
    SavingsReliability NVARCHAR(MAX) NULL,
    CostCoverageStatus NVARCHAR(MAX) NULL,
    MetricCollectionStatus NVARCHAR(MAX) NULL,
    MissingMetrics NVARCHAR(MAX) NULL,
    TagOwner NVARCHAR(MAX) NULL,
    MonthlyCost FLOAT NULL,
    CurrentSku NVARCHAR(MAX) NULL,
    CurrentVCpus FLOAT NULL,
    CurrentMemoryGB FLOAT NULL,
    PowerState NVARCHAR(MAX) NULL,
    Profile NVARCHAR(MAX) NULL,
    IsPrimaryProfile BIT NULL,
    TargetUtilizationPct FLOAT NULL,
    TargetSku NVARCHAR(MAX) NULL,
    TargetVCpus FLOAT NULL,
    TargetMemoryGB FLOAT NULL,
    ProjectedPeakPct FLOAT NULL,
    MonthlySavings FLOAT NULL,
    OfficialConservativeSavings FLOAT NULL,
    PerformanceRisk NVARCHAR(MAX) NULL,
    Status NVARCHAR(MAX) NULL
);
CREATE INDEX IX_FinOpsTargetOptionsAllRuns_ResourceId ON dbo.FinOpsTargetOptionsAllRuns (ResourceId);
CREATE INDEX IX_FinOpsTargetOptionsAllRuns_RunId ON dbo.FinOpsTargetOptionsAllRuns (RunId);
